import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { getFirestore, doc, getDoc, collection, getCountFromServer } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const VERSION='1.0.2';
const fbApp=initializeApp(firebaseConfig);
const auth=getAuth(fbApp);
const db=getFirestore(fbApp);
const root=document.getElementById('app');

const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function header(sub='Teams • Tournaments • Live Scoring'){return `<header class="hero"><div class="brand-row"><div class="logo-mark">🏏</div><div><h1 class="brand-title">CricTrack</h1><p class="brand-subtitle">${sub}</p></div></div></header>`}
function shell(content,sub){root.innerHTML=`<div class="app-shell">${header(sub)}${content}<footer class="footer">CricTrack v${VERSION} • Premium Cricket Platform</footer></div>`}

function home(){shell(`<main class="content"><h2 class="section-title">Welcome to CricTrack</h2><p class="section-copy">Choose your workspace to continue.</p><div class="grid"><button class="card" data-login="team"><div class="card-icon">🛡️</div><div class="card-title">Cricket Team</div><div class="card-copy">Team login, players, matches and scoring.</div></button><button class="card" data-login="tournament"><div class="card-icon">🏆</div><div class="card-title">Tournaments</div><div class="card-copy">Fixtures, live matches, points and results.</div></button></div><button class="super-admin" data-login="superadmin"><span>●</span> Super Admin</button></main>`);document.querySelectorAll('[data-login]').forEach(b=>b.onclick=()=>loginPage(b.dataset.login));}

function loginPage(role){
  if(role!=='superadmin'){
    const title=role==='team'?'Cricket Team Login':'Tournament Login';
    const label=role==='team'?'Team ID':'Tournament ID';
    shell(`<main class="login-wrap"><button class="back" id="back">← Back to Home</button><div class="login-card"><div class="login-badge">${role==='team'?'🛡️':'🏆'} &nbsp;Secure Login</div><h2 class="login-title">${title}</h2><p class="login-copy">${label} + Password login foundation is reserved for the next account-creation phase.</p><div class="note">Super Admin real Firebase login is active now. Team/Tournament accounts will be created securely from Super Admin in the next phase.</div></div></main>`,'Secure access portal');document.getElementById('back').onclick=home;return;
  }
  shell(`<main class="login-wrap"><button class="back" id="back">← Back to Home</button><form class="login-card" id="adminForm"><div class="login-badge">🔐 &nbsp;Secure Login</div><h2 class="login-title">Super Admin Login</h2><p class="login-copy">Use the Firebase Authentication email and password created for CricTrack Super Admin.</p><div class="field"><label>Admin Email</label><input id="email" type="email" autocomplete="username" placeholder="Enter admin email" required></div><div class="field"><label>Password</label><input id="password" type="password" autocomplete="current-password" placeholder="Enter password" required></div><label class="remember"><input id="showPw" type="checkbox"> Show password</label><button class="login-btn" id="loginBtn">Login Securely</button><div class="error" id="errorBox"></div><div class="note success-note">Firebase Authentication + Firestore Super Admin authorization are enabled.</div></form></main>`,'Super Admin secure portal');
  document.getElementById('back').onclick=home;document.getElementById('showPw').onchange=e=>document.getElementById('password').type=e.target.checked?'text':'password';document.getElementById('adminForm').onsubmit=adminLogin;
}

async function adminLogin(e){e.preventDefault();const btn=document.getElementById('loginBtn'),box=document.getElementById('errorBox');box.style.display='none';btn.disabled=true;btn.textContent='Checking secure access…';try{const cred=await signInWithEmailAndPassword(auth,document.getElementById('email').value.trim(),document.getElementById('password').value);const adminSnap=await getDoc(doc(db,'admins',cred.user.uid));if(!adminSnap.exists()||adminSnap.data().role!=='superadmin'){await signOut(auth);throw new Error('This account is not authorized as CricTrack Super Admin.');}await adminDashboard(cred.user);}catch(err){box.textContent=friendlyError(err);box.style.display='block';btn.disabled=false;btn.textContent='Login Securely';}}

function friendlyError(err){const c=err?.code||'';if(c.includes('invalid-credential')||c.includes('wrong-password')||c.includes('user-not-found'))return 'Email or password is incorrect.';if(c.includes('too-many-requests'))return 'Too many attempts. Please wait and try again.';if(c.includes('network-request-failed'))return 'Network problem. Check internet connection and try again.';return err?.message||'Login failed. Please try again.';}

async function adminDashboard(user){
  shell(`<main class="dashboard"><div class="topbar"><div><div class="admin-chip">🔐 SUPER ADMIN</div><h2 class="section-title" style="margin-top:10px">Control Centre</h2><p class="section-copy" style="margin-bottom:0">${esc(user.email||'Authorized admin')}</p></div><button class="logout" id="logout">Logout</button></div><div class="stats"><div class="stat"><div class="num" id="teamCount">—</div><div class="label">Cricket Teams</div></div><div class="stat"><div class="num" id="tournamentCount">—</div><div class="label">Tournaments</div></div><div class="stat"><div class="num">0</div><div class="label">Live Matches</div></div><div class="stat"><div class="num">0</div><div class="label">System Alerts</div></div></div><div class="admin-grid"><button class="admin-action red-accent"><div>🛡️</div><strong>Cricket Teams</strong><small>Create and manage team accounts.</small></button><button class="admin-action red-accent"><div>🏆</div><strong>Tournaments</strong><small>Create and manage tournament accounts.</small></button><button class="admin-action"><div>🏏</div><strong>Matches Control</strong><small>Platform match control centre.</small></button><button class="admin-action"><div>📡</div><strong>Live Monitoring</strong><small>Monitor active scoring sessions.</small></button><button class="admin-action"><div>🧾</div><strong>Audit Logs</strong><small>Track protected admin actions.</small></button><button class="admin-action"><div>⚙️</div><strong>System Settings</strong><small>Security and platform controls.</small></button></div><div class="status-row"><span class="dot"></span> Firebase secure connection active</div><div class="coming">Phase 2 foundation: real Super Admin login + authorization. Team/Tournament account creation comes next.</div></main>`,'Super Admin • Secure Control Centre');
  document.getElementById('logout').onclick=async()=>{await signOut(auth);home();};
  try{const [teams,tours]=await Promise.all([getCountFromServer(collection(db,'teams')),getCountFromServer(collection(db,'tournaments'))]);document.getElementById('teamCount').textContent=teams.data().count;document.getElementById('tournamentCount').textContent=tours.data().count;}catch{document.getElementById('teamCount').textContent='0';document.getElementById('tournamentCount').textContent='0';}
}

onAuthStateChanged(auth,async user=>{if(!user){home();return;}try{const s=await getDoc(doc(db,'admins',user.uid));if(s.exists()&&s.data().role==='superadmin'){adminDashboard(user);}else{await signOut(auth);home();}}catch{home();}});
